sudo: required
dist: trusty
language: node_js
node_js:
  - '12.0'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

services:
    - docker

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - docker build .
before_script:
    - npm install

script:
    - docker run -t gokulsubramani/angular-app -- --watch=false --code-coverage 
deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: "Docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-ap-south-1-914520140918"
    bucket_path: "Docker"
    on:
        branch: "master"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY