sudo: required
dist: trusty
language: node_js
node_js:
  - '12.0'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

services:
    - docker

before_install:
  #- docker build --tag gokulsubramani/angular-app .
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
script:
    - npm test
    - docker build --pull --cache-from gokulsubramani/angular-app --tag gokulsubramani/angular-app .
    #- docker run gokulsubramani/angular-app
    
after_success:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker tag angular-app $DOCKER_USERNAME/angular-app:latest
    - docker push $DOCKER_USERNAME/angular-app:latest
    #- docker run -t $DOCKER_USERNAME/angular-app 
deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: "angular-app"
    env: "AngularApp-env"
    bucket_name: "elasticbeanstalk-ap-south-1-914520140918"
    bucket_path: "angular-app"
    on:
        branch: "master"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"
after_deploy:
    - echo "done deploying"