version: '3'
services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "4204:4200"
        volumes: 
            - /app/node_modules
            - .:/app
